// This should come from KV store
export const securityHeaders = [
  {
    name: 'strict-transport-security',
    value: 'max-age=63072000; includeSubdomains; preload',
  },
  {
    name: 'content-security-policy',
    value: {
      'upgrade-insecure-requests': [],
      'default-src': [`'none'`],
      'base-uri': [`'none'`],
      'object-src': [`'none'`],
      'frame-ancestors': [`'none'`],
      'frame-src': [`'none'`],
      'child-src': [`'none'`],
      'img-src': [`'self'`],
      'prefetch-src': [`'self'`],
      'media-src': [`'self'`],
      'font-src': [`'self'`],
      'connect-src': [`'self'`],
      'navigate-to': [`'self'`],
      'form-action': [`'self'`],
      'manifest-src': [`'self'`],
      'worker-src': [`'self'`],
      'script-src': [
        `'self'`,
        `'unsafe-inline'`,
        `https:`,
        `'report-sample'`,
        `'strict-dynamic'`,
        `'nonce'`,
      ],
      'script-src-elem': [
        `'self'`,
        `'unsafe-inline'`,
        `https:`,
        `'report-sample'`,
        `'strict-dynamic'`,
        `'nonce'`,
      ],
      'script-src-attr': [
        `'self'`,
        `'unsafe-inline'`,
        `https:`,
        `'report-sample'`,
        `'strict-dynamic'`,
        `'nonce'`,
      ],
      'style-src': [
        `'self'`,
        `'unsafe-inline'`,
        `https:`,
        `'report-sample'`,
        `'strict-dynamic'`,
        `'nonce'`,
        `'inline-hash'`,
      ],
      'style-src-elem': [
        `'self'`,
        `'unsafe-inline'`,
        `https:`,
        `'report-sample'`,
        `'strict-dynamic'`,
        `'nonce'`,
      ],
      'style-src-attr': [`'unsafe-hashes'`, `'inline-hash'`],
      'report-uri': [`https://vinaypuppal.report-uri.com/r/d/csp/reportOnly`],
    },
  },
  {
    name: 'feature-policy',
    value: {
      accelerometer: ["'none'"],
      camera: ["'none'"],
      geolocation: ["'none'"],
      gyroscope: ["'none'"],
      magnetometer: ["'none'"],
      microphone: ["'none'"],
      payment: ["'none'"],
      usb: ["'none'"],
    },
  },
  { name: 'X-Content-Type-Options', value: 'nosniff' },
  { name: 'X-Frame-Options', value: 'DENY' },
  { name: 'X-XSS-Protection', value: '1; mode=block' },
  { name: 'Referrer-Policy', value: 'same-origin' },
];
